### ISSUE TITLE
How can I customize the heading levels?

### ISSUE THREAD

**Issue by davidsneighbour** [conventional-changelog/standard-version#775] opened 2021-06-22 12:44 UTC
I am using standard-version with no specific setup regarding the CHANGELOG creation and my changelogs end up somewhere along the lines of the following:

```markdown
# Changelog

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

### [1.0.33](https://github.com/dnb-hugo/components/compare/functions/v1.0.32...functions/v1.0.33) (2021-06-21)


### Chore

* update README.md ([accbaa4](https://github.com/dnb-hugo/components/commit/accbaa4fb080e090b30bb4f21fdda8a84dc12fa4))
```

I would expect the heading level of 1.0.33 to be just two ##. Is there a way to configure this properly?

I don't think any of the settings in my config influences that:

```
module.exports = {
  // for available options see https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md
  // skip: {
  //   changelog: true,
  // },
  scripts: {
    prerelease: "./bin/release-hook-prerelease.sh",
  },
  bumpFiles: [
    {
      filename: "package.json",
      type: "json",
    },
  ],
  types: [
    { type: "feat", section: "Features" },
    { type: "fix", section: "Bug Fixes" },
    { type: "docs", section: "Documentation" },
    { type: "style", section: "Styling" },
    { type: "refactor", section: "Refactors" },
    { type: "perf", section: "Performance" },
    { type: "test", section: "Tests" },
    { type: "build", section: "Build System" },
    { type: "ci", section: "CI" },
    { type: "chore", section: "Chore" },
    { type: "revert", section: "Reverts" },
  ],
};
```

**Comment by josteph** [comment] 2021-07-04 03:42
I think this is a duplicate of https://github.com/conventional-changelog/standard-version/issues/317

As of now, there is no way to change the heading level from the CLI config.

**Closed** 2021-08-02 03:52 UTC
Labels: question
