### ISSUE TITLE
RC Support

### ISSUE THREAD

**Issue by DxCx** [conventional-changelog/standard-version#109] opened 2016-09-22 06:27 UTC
Hi,

i thought about it and i think that there is a need to define an RC release,
so for example, after the next version calculation, it will append -rc.1 to it,
if rc.1 exists it will incremeant the number.
and then once standard-version is run without the --rc keyword it will release the real version that suppose to to be released.

thoughts?

**Comment by Tapppi** [comment] 2016-09-22 17:38
Duplicate of #83, complain and reopen if I got it wrong.

**Closed by Tapppi** 2016-09-22 17:38 UTC

**Comment by DxCx** [comment] 2016-09-22 17:50
Yep you are correct that will do, didnt got the context when reading subjects..

Thanks!
