### ISSUE TITLE
Support pre release

### ISSUE THREAD

**Issue by rewop** [conventional-changelog/standard-version#105] opened 2016-09-15 13:59 UTC
I have been using standard-version now for a few weeks, and I realised that there is no support for pre-releases such as `1.0.0-alpha-1`, `2.0.0-beta-1` (AFAIK).

Is there any plan to support them?

**Comment by stevemao** [comment] 2016-09-15 23:40
duplicate of #83 ?

**Comment by rewop** [comment] 2016-09-16 06:45
That is exactly what I meant. Didn't search the PRs apparently. To me this can be closed once the PR is merged.

**Comment by stevemao** [comment] 2016-09-16 07:56
Let's move the discussion there :)

**Closed by stevemao** 2016-09-16 07:56 UTC
