### ISSUE TITLE
Chores section

### ISSUE THREAD

**Issue by mrtnbroder** [conventional-changelog/standard-version#135] opened 2016-10-28 11:51 UTC
When looking at https://github.com/conventional-changelog/standard-version/blob/master/CHANGELOG.md, I can see that there is indeed a Chores section, but it looks like I have to add an additional flag or something to generate it. Out of the box, I get no Chores section for my changelog generation.

Since the whole changelog generation is spread across thousands of repos (I'm exaggerating, but it feels much like it)
`conventional-changelog`, `conventional-changelog-core`, `conventional-changelog-cli`, `conventional-changelog-preset-angular` and what not, it's **really hard and frustrating** to understand and follow the codebase. Especially when trying to understand the README's. As every module is linking to some other module which actually has the information I want/need (maybe).

I could not find a flag or something that I could add to the  `standard-version` cli to generate the `Chores` section as well.

**Comment by Tapppi** [comment] 2016-10-28 13:12
Yes that chore is there because it is the cause of the Breaking Change. @stevemao @bcoe can you comment on this, I have no strong opinions on the subject, but I remember there being discussions about this.

**Comment by nexdrew** [comment] 2016-10-28 13:51
Typically, commits marked as **chore** do not end up in the CHANGELOG by default. Since the CHANGELOG file is [always included](https://docs.npmjs.com/files/package.json#files) in the published package, the idea is to strike a balance between including the important changes (in an easy to read/render format) and keeping the file to a reasonable size. If _all_ changes were included, it would essentially duplicate the entire git log.

As @Tapppi mentioned, the only reason that chore ended up in the CHANGELOG is because it was also marked as a **BREAKING CHANGE**, which is a little odd but understandable.

AFAIK, there is currently no way to tell `standard-version` to explicitly include chore commits (or anything other than **feat**, **fix**, and **BREAKING CHANGE**). This is the standard/convention, and `standard-version` aims to be an opinionated tool that encourages the use of that standard/convention. If you want the commits to be included in the CHANGELOG, you should use one of these labels.

That being said, I agree it would be nice to allow the convention to be overridden or augmented via CLI option, but I don't think `standard-version` is the tool to do that. (I also agree that the code is scattered amongst ETOOMANYPACKAGES, which _does_ make it difficult to add certain features to `standard-version`, but, for better or worse, this is the current state of the world until someone - like myself - has the time and energy to change it.)

**Comment by stevemao** [comment] 2016-10-28 21:28
see https://github.com/angular/angular/issues/5672
Normally chores don't make any difference to the end user of your app. You shouldn't make a release after only chores, style changes or code refactors.

**Comment by bcoe** [comment] 2016-11-26 22:01
@stevemao @nexdrew @Tapppi, my preference would be to not add an additional configuration setting for toggling CHANGELOG content -- in the name of minimal configuration.

Having said this, what might be nice would be to introduce a setting to allow folks to pass their own template -- would this give people enough to fork standard-version easily, and introduce their own set of conventions?

**Comment by stevemao** [comment] 2016-11-27 09:46
Linking https://github.com/conventional-changelog/conventional-changelog/pull/146 for folks who would like to use their own conventions. The issue isn't the exactly same, but maybe an option.

**Comment by Tapppi** [comment] 2016-12-23 15:51
So I though about this a bit after @bcoe mentioned allowing a standard-version config stanza in package.json in . This could easily be supported by allowing a `preset` option (e.g. `"preset": "custom1"` would use `conventional-changelog-custom1` as the preset), as [conventional-changelog looks for the preset as a normal package](https://github.com/conventional-changelog/conventional-changelog/blob/master/index.js#L9). /cc @bcoe @stevemao ?

**Comment by bcoe** [comment] 2017-03-29 22:02
@Tapppi I definitely like the idea of starting to expose some config options 👍 you should be able to use the https://github.com/yargs/yargs#pkgconfkey-cwd functionality in yargs to facilitate this.

---

_However_ (cue ominous music)., here's why I think we need something _like_ a chores stanza; one of the frequent ways I break a release is by pulling in a dependency update, which has an unexpected breaking change -- tools like greenkeeper flag these updates as a chore, so using the angular commit format there's little forensic information in logs when these errors occur.

Is there another prefix we could flag library updates with, that we could show in the CHANGELOG? tldr; I think library updates should almost always show in CHANGELOG, but other chores should not -- makes me think maybe they should be flagged instead as a fix, feat, or breaking?

**Comment by Tapppi** [comment] 2017-03-30 15:18
@bcoe Having all dependency upgrades in the changelog is a LOT of potential noise for some projects. The problem is separating the meaningful from the unmeaningful, but that is a hard problem.

**Comment by bcoe** [comment] 2019-05-05 22:00
@mrtnbroder you can now configure which sections are displayed with a `.versionrc` in `standard-version@6.0.1`, using the variable `types`; let me know if this does the trick for you.

**Closed by bcoe** 2019-05-05 22:00 UTC
Labels: discussion
