### ISSUE TITLE
version 7 ignores features and releases fixes instead of minors

### ISSUE THREAD

**Issue by m8ms** [conventional-changelog/standard-version#472] opened 2019-10-29 14:26 UTC
Scenario:
1. a couple of `feat: xxxx` commits
2. `standard-version --first-run` generates: `v0.0.1`
3. a couple of new`feat: xxxx` commits
4. `standard-version` generates: `v0.0.2`
5. `CHANGELOG.md` shows changes as features nevertheless.

In this scenario version _standard-version@6.0.1_ works fine - releases `v0.1.0`, and then `v0.2.0`

Am I missing something?
Example: https://github.com/m8ms/getmrs

**Comment by tommywo** [comment] 2019-10-29 17:03
Duplicate of:
https://github.com/conventional-changelog/standard-version/issues/460
https://github.com/conventional-changelog/standard-version/issues/449
https://github.com/conventional-changelog/standard-version/issues/429
https://github.com/conventional-changelog/standard-version/issues/422

**Closed by tommywo** 2019-10-29 17:03 UTC
