### ISSUE TITLE
Handling versions below 1.0.0

### ISSUE THREAD

**Issue by azachar** [conventional-changelog/standard-version#131] opened 2016-10-19 04:56 UTC
Hi There, 
Please do you support a different handling model for version under 1.0.0?

NPM for example treats **^**0.1.0 as **~**0.1.0 for all versions bellow 1.0.0

https://docs.npmjs.com/misc/semver

```
~1.2.3 := >=1.2.3 <1.(2+1).0 := >=1.2.3 <1.3.0
~1.2 := >=1.2.0 <1.(2+1).0 := >=1.2.0 <1.3.0 (Same as 1.2.x)
~1 := >=1.0.0 <(1+1).0.0 := >=1.0.0 <2.0.0 (Same as 1.x)
~0.2.3 := >=0.2.3 <0.(2+1).0 := >=0.2.3 <0.3.0

^1.2.3 := >=1.2.3 <2.0.0
^0.2.3 := >=0.2.3 <0.3.0
^0.0.3 := >=0.0.3 <0.0.4

```

So upgrade a minor number only if there is a breaking change. Otherwise patch number is increased.

Thanks a lot!

Best regards,
Andrej

**Comment by tunnckoCore** [comment] 2016-11-17 02:50
I'm also curious on similar thing. How to bump from below v1 to v1? I mean, I know how - one way could be to make fake/empty commit with "BREAKING CHANGE" but.. in reality it isn't a breaking change, it is just time for v1 and there is stable api and everything. It's just my practice to NOT tag releases before v1 and in most cases I don't use standard-version when i have v0.x. Just doing few v0.x versions, while updating docs, and api, then instantly release v1 and then i just start using standard-version and follows the standards and semver.

It may be side question, but...

**Comment by tleunen** [comment] 2016-11-17 15:19
The issue is actually inside semver (see https://github.com/npm/node-semver/issues/177)

But I agree... How to upgrade/increment from 0.x to 1.0..

If you're on a 0.5.0 for example and make a breaking change, the next version should only be 0.6.0, not 1.0

**Comment by bcoe** [comment] 2016-11-26 21:58
I know not 100% of folks agree, but I'm definitely of the school of thought that, versions are cheap, just make your first library version `v1.0.0`. Maybe we could write this into the README as part of our opinionated guidelines.

I understand the other arguments, folks don't want to announce their library as stable when it's in an extreme amount of flux, _but_ I think it's not worth the edge-cases it creates around semver. Better that while your library is in flux, IMO, you bump a few majors.

**Comment by Tapppi** [comment] 2016-12-01 18:56
I have to agree with @bcoe here, this conversation has happened a lot in the past, and my opinion is that packages should stay in the `v0.x` phase a short enough time that this isn't a problem. When your API is not changing in extremes, it's time for `v1.x` and possibly a few faster than par major bumps for any API changes deemed necessary. Look at `nyc` and  the `hapijs` ecosystem for packages that do frequent than usual major bumps.

For reference, this is an excerpt from a long post against SemVer by `underscore`s author: 

> Keeping a system that's in heavy production use at pre-1.0 levels for many years is effectively the same thing as not using SemVer in the first place.

This is in reference to Node.js being <1.0 for so long, and I whole heartedly agree. If you are using the package in production for extended periods, it should move to >1.0. If the API isn't final at that point, that should IMO be a wake up call for the API to be locked down asap for a quick 2.0 instead of having wonky <1.0 semantics. There are of course some exceptions to this rule, e.g. a popular monolithic tool in heavy development that cannot in any good consciousness call itself stable but is still used in production (see the future of the `yarn` package manager for example). 

The other alternative is to use a lot of `v0.x.0` versions, and quickly iterate on them until you reach a stable API. This is what Google does, and I respect anyones wishes to do that but I personally do not see it as a good way to develop an API that is used in production.

**Comment by Tapppi** [comment] 2016-12-02 19:47
I'm leaving this open for a while with the `wontfix` label. If there is no discussion for a while, any maintainers should feel free to close. The question about bumping from  0.x to 1.0 is solved by adding any `BREAKING CHANGE` to the release.. Might not be ideal, I'm up for discussions on that, but otherwise I think this is just not something we want to focus on?

**Comment by bcoe** [comment] 2016-12-04 18:42
@Tapppi I agree with your plan. I think we should strive to solve to adhere to the `80/20` rule; solve the happy path workflow as elegantly as possible, and help guide people to it, don't go down a rabbit hole of edge-cases.

I do think we should try to make it easy, and documented, as to how folks can use standard-version as a starting point, and extend it to their own workflow though.

**Comment by Tapppi** [comment] 2017-02-23 13:13
Closing due to inactivity

**Closed by Tapppi** 2017-02-23 13:13 UTC
Labels: discussion, wontfix

**Comment by stevemao** [comment] 2017-02-26 07:15
I want to support it in [conventional-recommended-bump](https://github.com/conventional-changelog/conventional-recommended-bump/issues/24). But it'll probably still be a wontfix here since it still requires some config in the parent module.

**Comment by eisenreich** [comment] 2022-02-01 07:23
I started with a new repository and I would also start with version `0.1.0` - the version number is the `version.txt`, configured with `bumpFiles`.

If you like to release the first version with `0.1.0`, just use the following:
```
npx standard-version --release-as 0.1.0
```

this should release the first version with 0.1.0 and then you can just use

```
npx standard-version
```

which should bump the version according the SemVer logic - also < 1.0.0 versions.
