### ISSUE TITLE
Multiple h1s in Changelog - there should only be one

### ISSUE THREAD

**Issue by marcysutton** [conventional-changelog/standard-version#208] opened 2017-09-01 17:35 UTC
The HTML output in the change logs produced by this tool include too many h1 elements. There should be one at the top for "Change Log", and the individual releases should be h2's so the content hierarchy makes sense and follows best practices for accessible headings.

Here's what it outputs now:
```
# Change Log

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

<a name="3.0.0-alpha.2"></a>
# [3.0.0-alpha.2](https://github.com/dequelabs/axe-core/compare/v3.0.0-alpha.1...v3.0.0-alpha.2) (2017-09-01)

### Bug Fixes
```

Here's what it should be: 
```
# Change Log

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

<a name="3.0.0-alpha.2"></a>
## [3.0.0-alpha.2](https://github.com/dequelabs/axe-core/compare/v3.0.0-alpha.1...v3.0.0-alpha.2) (2017-09-01)

### Bug Fixes
```

I couldn't figure out where those come from after a quick look through the source, perhaps it's from one of the dependent modules? I'm happy to submit a PR if someone can point me in the right direction (including to another repo, if needed).

**Comment by ungoldman** [comment] 2017-09-01 20:26
100% agree! I filed an issue here: https://github.com/conventional-changelog/conventional-changelog/issues/214

The response I got indicated that this is by design, and that it's determined by this template file:

https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-writer/templates/header.hbs

I would very much like to standardize around a more semantic convention (h1 for title, h2 for version section, h3-6 for headings specific to a version).

**Comment by marcysutton** [comment] 2017-09-01 20:56
Thanks! I added a comment over there.

**Comment by bcoe** [comment] 2017-09-03 21:08
@marcysutton @ungoldman for the record, I'm definitely in favor of us having valid markup! and would happily help land any tickets related to this.

**Comment by stevemao** [comment] 2017-09-04 05:10
Probably we don't need `# Change Log` at the top since the filename already suggests that?

**Comment by ungoldman** [comment] 2017-10-16 03:55
PR opened here: https://github.com/conventional-changelog/conventional-changelog/pull/237

**Comment by aaronjameslang** [comment] 2018-06-07 20:55
So we need to bump the version of `conventional-changelog` `standard-version` depends on. Should we update all the deps while we're at it? Looks like it might require a major version bump, would there be resistance to this?

**Comment by naltatis** [comment] 2018-10-10 14:10
Any plans on upgrading to latest `conventional-changelog`? I ran into the same issue.

**Comment by NateScarlet** [comment] 2019-03-29 05:36
Same issue
Using `postchangelog` hook for standard-version@5.0.2

```sh
sed -e '2,${s/^# /## /}' -e 's/Change Log/Changelog/' -i CHANGELOG.md
```

**Comment by bcoe** [comment] 2019-04-04 17:43
@NateScarlet is the fix simply upgrading the version of conventional-changelog? will do so soon, working on a release with a few exciting things.

**Comment by bcoe** [comment] 2019-05-05 22:23
This should now be fixed as of `standard-version@6.x.x` thanks for reporting the issue @marcysutton 👍

**Closed by bcoe** 2019-05-05 22:23 UTC
