### ISSUE TITLE
As a replacement of npm version, there is no control with the version?

### ISSUE THREAD

**Issue by e-cloud** [conventional-changelog/standard-version#107] opened 2016-09-19 07:55 UTC
`npm version` allows me to control the version to be a major/minor/patch release.

But `standard-version` just bump the major version part, like `v1.2.0 => v2.0.0`

**Comment by stevemao** [comment] 2016-09-20 00:11
duplicate of https://github.com/conventional-changelog/standard-version/issues/84?

**Comment by Tapppi** [comment] 2016-09-20 08:27
@e-cloud That is the point of `standard-version` though. It analyzes your commit messages and bumps accordingly. Is your issue with the basic functionality or a specific version that is being bumped incorrectly? Although #84 is nice, and should probably be supported 😄

**Comment by ggranum** [comment] 2016-09-20 08:32
@Tapppi Not really usable without ability to specify the granularity of the bumps. I can't rev my primary version every time I add a breaking change to master. I'll be on version 42.12.0 before I even issue a beta :~)

**Comment by e-cloud** [comment] 2016-09-20 08:33
The basic is right, but i need to do some thing like prerelease(#105 #83). The `conventional-recommended-bump` can't control that.

**Comment by Tapppi** [comment] 2016-09-20 09:20
@ggranum @e-cloud So this is a combination of #83 and #84? #83 should make it possible to do pre-releases and #84 is just a previous issue on the `releaseAs` option. We can close this as a duplicate and move the discussion there?

**Comment by stevemao** [comment] 2016-09-20 11:32
reopen if anyone disagree :)

**Closed by stevemao** 2016-09-20 11:32 UTC
