### ISSUE TITLE
Named versions

### ISSUE THREAD

**Issue by AntJanus** [conventional-changelog/standard-version#118] opened 2016-10-04 09:07 UTC
It's pretty common to have named version bumps (like `2.2.0-RC` or `15.0.0-some-obscure-pop-culture-reference`). Is there a way to easily add a suffix to the version bumps? Or get a suggested release \# and then run a release with my own custom version name?

**Comment by stevemao** [comment] 2016-10-04 09:27
duplicate of https://github.com/conventional-changelog/standard-version/pull/83?

**Comment by Tapppi** [comment] 2016-10-04 09:40
Yes this is duplicate of #83 and maybe #84 partially?

**Closed by Tapppi** 2016-10-04 09:40 UTC

**Comment by AntJanus** [comment] 2016-10-04 14:59
Thanks! I read over it and wasn't sure if it applied to what I was asking about.
